const ENUM_ENVIRONMENT = ['DEVELOPMENT', 'TEST', 'STAGING', 'PRODUCTION'];
const ENUM_EXPLOITABILITY = ['EXPLOITABLE', 'NOT_EXPLOITABLE', 'UNDER_INVESTIGATION', 'UNKNOWN'];
const ENUM_ASSET_CRITICALITY = ['LOW', 'MEDIUM', 'HIGH', 'CRITICAL'];
const ENUM_INTERNET_EXPOSURE = ['NONE', 'INTERNAL', 'RESTRICTED_PUBLIC', 'PUBLIC'];
const ENUM_PRIVILEGE_LEVEL = ['UNPRIVILEGED', 'ELEVATED', 'SYSTEM'];
const ENUM_DATA_SENSITIVITY = ['PUBLIC', 'INTERNAL', 'CONFIDENTIAL', 'RESTRICTED'];
const ENUM_RUNTIME_EXECUTION = ['EXECUTED', 'PRESENT_NOT_EXECUTED', 'NOT_PRESENT', 'UNKNOWN'];
const ENUM_COMPONENT_PRESENCE = ['PRESENT', 'NOT_PRESENT', 'PARTIAL', 'UNKNOWN'];
const ENUM_VEX_APPLICABILITY = ['AFFECTED', 'NOT_AFFECTED', 'FIXED', 'UNDER_INVESTIGATION', 'UNKNOWN', 'NOT_AVAILABLE'];
const ENUM_EXCEPTION_STATUS = ['NONE', 'ACTIVE', 'EXPIRED', 'REVOKED', 'OUT_OF_SCOPE', 'INVALID'];

const ENUM_CONTEXTUAL_RISK = ['LOW', 'MEDIUM', 'HIGH', 'CRITICAL', 'UNKNOWN'];
const ENUM_POLICY_BLOCKING_STATUS = ['NON_BLOCKING', 'BLOCKING', 'REVIEW_REQUIRED'];
const ENUM_ASSURANCE_STATE = ['VERIFIED_TRUSTED', 'VERIFIED_UNTRUSTED', 'INVALID', 'MISSING', 'STALE', 'CONFLICTING', 'NOT_APPLICABLE', 'NOT_EVALUATED'];

module.exports = {
  ENUM_ENVIRONMENT,
  ENUM_EXPLOITABILITY,
  ENUM_ASSET_CRITICALITY,
  ENUM_INTERNET_EXPOSURE,
  ENUM_PRIVILEGE_LEVEL,
  ENUM_DATA_SENSITIVITY,
  ENUM_RUNTIME_EXECUTION,
  ENUM_COMPONENT_PRESENCE,
  ENUM_VEX_APPLICABILITY,
  ENUM_EXCEPTION_STATUS,
  ENUM_CONTEXTUAL_RISK,
  ENUM_POLICY_BLOCKING_STATUS,
  ENUM_ASSURANCE_STATE
};
